### ISSUE TITLE
初始化失败问题

### ISSUE THREAD

**Issue by xluu233** [idisfkj/android-startup#22]
您好，我在Android9.0的设备上使用startup遇到初始化失败的问题。后来换用您的这个库，依然有相似的问题：

Android10和Android11是ok的

代码如下：
```
        <provider
            android:name="com.rousetime.android_startup.provider.StartupProvider"
            android:authorities="${applicationId}.android_startup"
            android:exported="false">

            <meta-data
                android:name="com.example.xlulibrary.ToastLifecycle"
                android:value="android.startup" />

        </provider>

```
```
internal object ToastLifecycle : AndroidStartup<Unit>() {

    lateinit var application: Application

    override fun callCreateOnMainThread(): Boolean = false

    override fun create(context: Context) {
        application = context as Application
    }

    override fun dependencies(): List<Class<out Startup<*>>>? = null

    override fun waitOnMainThread(): Boolean = false
}
```

log如下：
```
2021-12-03 17:30:32.927 9659-9659/com.example.toastbox E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.toastbox, PID: 9659
    java.lang.RuntimeException: Unable to get provider com.rousetime.android_startup.provider.StartupProvider: com.rousetime.android_startup.execption.StartupException: java.lang.IllegalAccessException: Class java.lang.Class<com.rousetime.android_startup.StartupInitializer> cannot access private  method void com.example.xlulibrary.ToastLifecycle.<init>() of class java.lang.Class<com.example.xlulibrary.ToastLifecycle>
        at android.app.ActivityThread.installProvider(ActivityThread.java:6396)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: com.rousetime.android_startup.execption.StartupException: java.lang.IllegalAccessException: Class java.lang.Class<com.rousetime.android_startup.StartupInitializer> cannot access private  method void com.example.xlulibrary.ToastLifecycle.<init>() of class java.lang.Class<com.example.xlulibrary.ToastLifecycle>
        at com.rousetime.android_startup.StartupInitializer.discoverAndInitialize$android_startup_release(StartupInitializer.kt:55)
        at com.rousetime.android_startup.provider.StartupProvider.onCreate(StartupProvider.kt:19)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1919)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1894)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6391)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.lang.IllegalAccessException: Class java.lang.Class<com.rousetime.android_startup.StartupInitializer> cannot access private  method void com.example.xlulibrary.ToastLifecycle.<init>() of class java.lang.Class<com.example.xlulibrary.ToastLifecycle>
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at com.rousetime.android_startup.StartupInitializer.discoverAndInitialize$android_startup_release(StartupInitializer.kt:43)
        at com.rousetime.android_startup.provider.StartupProvider.onCreate(StartupProvider.kt:19) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1919) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1894) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:6391) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2021-12-03 17:30:32.934 9659-9659/com.example.toastbox I/Process: Sending signal. PID: 9659 SIG: 9

```

希望大佬能看下😄

**Comment by idisfkj** [comment]
将`internal object ToastLifecycle`转化成`internal class ToastLifecycle`

**Comment by xluu233** [comment]
感谢大佬！😎
